### ISSUE TITLE
How to cite MSDeisotope

### ISSUE THREAD

**Issue by JeffEdge** [mobiusklein/ms_deisotope#15]
Hi!
How do you want you work to be cited?
Thank you!

**Comment by mobiusklein** [comment]
Writing a manuscript dedicated to `ms_deisotope` has been on my todo list for nearly two years. I can create a Zenodo DOI for the codebase within the next 16 hours though.

If you'd rather cite an article, it is described briefly in 
> Klein, J., Carvalho, L., & Zaia, J. (2018). Application of network smoothing to glycan LC-MS profiling. Bioinformatics, 34(20), 3511–3518. https://doi.org/10.1093/bioinformatics/bty397

but that article has *a lot* of other things going on in it and may not be a good source.

**Comment by JeffEdge** [comment]
A Zenodo DOI for the codebase would be perfect. I still need to iron out a few things so there is no hurry.
Thanks!

**Comment by mobiusklein** [comment]
[![DOI](https://zenodo.org/badge/52416024.svg)](https://zenodo.org/badge/latestdoi/52416024)

**Comment by JeffEdge** [comment]
Thanks
