### ISSUE TITLE
Could not be located in the test suite's data package

### ISSUE THREAD

**Issue by yachliu** [mobiusklein/ms_deisotope#26]
```python import ms_deisotope
from ms_deisotope.test.common import datafile

%matplotlib inline

from matplotlib import pyplot as plt, rcParams
rcParams['figure.figsize'] = 16, 4

# We'll use the datafile helper to locate the package test data for demonstration purposes
path = datafile("three_test_scans.mzML")
reader = ms_deisotope.MSFileLoader(path)
```

Exception: The path '/home/xcq/anaconda3/envs/diapasef_proc/lib/python3.8/site-packages/ms_deisotope/test/test_data/three_test_scans.mzML' could not be located in the test suite's data package.If you are NOT running the ms_deisotope test suite, you should not be using this function.

**Comment by mobiusklein** [comment]
This is something I should have addressed a long time ago. These data files are just a bit too large to include in the PyPI distribution that you install with `pip`, but are included in the source repository on GitHub. I've just added a feature to `ms_deistope.test.common.datafile` to automatically download data files when they cannot be found locally.

**Comment by yachliu** [comment]
> This is something I should have addressed a long time ago. These data files are just a bit too large to include in the PyPI distribution that you install with `pip`, but are included in the source repository on GitHub. I've just added a feature to `ms_deistope.test.common.datafile` to automatically download data files when they cannot be found locally.

Thank you very much!
