### ISSUE TITLE
Pyteomics version pinning in setup.py

### ISSUE THREAD

**Issue by joewandy** [mobiusklein/ms_deisotope#30]
Hi @mobiusklein, hope you're doing well.

For ms_deisotope 0.0.53, I noticed pyteomics is pinned to 4.6.0 in setup.py
https://github.com/mobiusklein/ms_deisotope/blob/master/setup.py#L277

But the latest version of pyteomics (4.6.2), released 3 weeks ago, seems to have fixed a number of issues that you raised. Is it now possible to remove that version pinning so we can install pyteomics 4.6.2 alongside ms_deisotope?

Thanks, and have a nice day!!

Joe

**Comment by mobiusklein** [comment]
Version 0.0.53 is now live on PyPI (https://pypi.org/project/ms-deisotope/) that should allow `pyteomics>=4.6.2`

**Comment by joewandy** [comment]
Thanks a lot!!
