### ISSUE TITLE
Installing ms_deisotope, get warning "The C extension could not be compiled"

### ISSUE THREAD

**Issue by azzamallow** [mobiusklein/ms_deisotope#4]
I am trying to install ms_deisotope on my ubuntu machine, using python3.6. I checkout the code and run:

```python3 setup.py install```

results in:

```
Version is: '0.0.6'
local variable 'macros' referenced before assignment
Version is: '0.0.6'
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info

...

Using /home/ubuntu/.local/lib/python3.6/site-packages
Finished processing dependencies for ms-deisotope==0.0.6
***************************************************************************
WARNING: The C extension could not be compiled, speedups are not enabled.
Plain-Python build succeeded.
***************************************************************************
```

How do I install ms_deisotope on my machine, with C extensions compiled?

**Comment by mobiusklein** [comment]
Thank you for reporting this. I had a mistake in my `setup.py` script. I'll fix that shortly. In the meantime, you can work around the problem by installing Cython when building from source.

**Comment by mobiusklein** [comment]
I've included the fix in commit d97f0e679d1e38eed40888f1b5b6009572ba4f6e.

**Comment by mobiusklein** [comment]
@azzamallow can you confirm whether that change fixed the problem, please?

**Comment by azzamallow** [comment]
@mobiusklein sorry for the late reply, yes the changes fixed the problem. Thanks!
