### ISSUE TITLE
Errors on import

### ISSUE THREAD

**Issue by DarylWM** [mobiusklein/ms_deisotope#8]
I did a plain Python install on Python 2.7, and when I do the import I get these errors:

```
>>> import ms_deisotope
No module named composition
(ImportError('No module named averagine',), 'averagine')
No module named scoring

```

Have I missed a step somewhere?

**Comment by mobiusklein** [comment]
Those indicate that the C-extensions for one or more libraries failed to import. This looks like the `brainpy` and `ms_deisotope` C extensions failed to import. Do you know if there were errors during their compilation?

**Comment by DarylWM** [comment]
To get going I was aiming for a plain Python install - the C extensions weren't compiled. I missed the ms_peak_picker and brainpy dependencies, but all good now. Thanks!

**Comment by DarylWM** [comment]
I went back and installed ms_peak_picker, brainpy, and ms_deisotope with C extensions compiled, and I still get an error on import. I'm using Python 2.7.15

```
>>> import ms_deisotope
No module named composition
(ImportError('No module named composition',), 'averagine')
No module named composition

```

**Comment by mobiusklein** [comment]
That looks like the `brainpy` C extensions still aren't being found. To confirm, try running `python -c "from brainpy._c import composition"`

**Comment by DarylWM** [comment]
It seems I messed up my environment along the way. I scratched it and started again, and now it's fine. Thanks for your help Joshua.
